module.exports = {
	BINARY_OPERATION: "BINARY_OPERATION",
	EXPRESSION: "EXPRESSION",
	NUMBER: "NUMBER",
	STRING: "STRING",
	REFERENCE: "REFERENCE",
	BOOLEAN: "BOOLEAN",
	OPERATOR: "OPERATOR",
	STATEMENT: "STATEMENT",
	ASSIGNMENT: "ASSIGNMENT",
	BLOCK: "BLOCK",
	COMPARISON: "COMPARISON"
};